<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información General</a></li>
            <li><a href="#tab2" data-toggle="tab">Información Bancaria</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('duenio.razon_social', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Razon Social'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::text('duenio.identificacion', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Identificacin'); ?>
                    </div>
                </div>
            </div>

            <div class="tab-pane" id="tab2">



                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::dbSelect('duenio.banco_id', array('nombre'), array('stti/banco', 'getListadoBancos'), array('todas'=>'Todos'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Banco'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::text('duenio.tipo_cuenta', array('class'=>'input-xxlarge input-required mask-alphanum show-error input-user'), NULL, 'Tipo de Cuenta'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::number('duenio.numero_cuenta', array('class'=>'input-numeric show-error input-required'), NULL, 'Numero de Cuenta del Banco'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar usuario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('sistema/usuario/listar/'); ?>
                    </div>

                </div>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
