<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <fieldset class="fieldset">
                    <legend>Informaci&oacute;n Personal</legend>
                    <div class='row-fluid'>
                        <div class="span4">
                            <?php echo DwForm::text('duenio.razon_social', NULL, $duenio->razon_social, 'Razon Social'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('duenio.identificacion', NULL, $duenio->identificacion, 'Identificacin'); ?>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="fieldset">
                    <legend>Informaci&oacute;n Bancaria</legend>
                    <div class='row-fluid'>
                        <div class="span4">
                            <?php echo DwForm::dbSelect('duenio.banco_id', array('nombre'), array('stti/banco', 'getListadoBancos'), array('todas'=>'Todos'), NULL, $duenio->banco_id, 'Banco'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('duenio.tipo_cuenta', NULL, $duenio->tipo_cuenta, 'Tipo de Cuenta'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::number('duenio.numero_cuenta', NULL, $duenio->numero_cuenta, 'Numero de Cuenta del Banco'); ?>
                        </div>
                    </div>
                </fieldset>
                <div class="row-fluid">
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar usuario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('stti/duenios/listar/'); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
