<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <?php echo DwForm::hiddenKey('duenio.id', $duenio->id)?>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <fieldset class="fieldset">
                    <legend><small>Informaci&oacute;n Personal</small></legend>
                    <div class='row-fluid'>
                        <div class="span4">
                            <?php echo DwForm::text('duenio.razon_social', array('class' => 'input-required mask-alphanum show-error'), $duenio->razon_social, 'Razon Social'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('duenio.identificacion', array('class' => 'input-required mask-alphanum show-error'), $duenio->identificacion, 'Identificacin'); ?>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="fieldset">
                    <legend><small>Informaci&oacute;n Bancaria</small></legend>
                    <div class='row-fluid'>
                        <div class="span4">
                            <?php echo DwForm::dbSelect('duenio.banco_id', array('nombre'), array('stti/banco', 'getListadoBancos'), array('todas'=>'Todos'), array('class' => 'input-required mask-int show-error'), $duenio->banco_id, 'Banco'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::dbSelect('duenio.tipo_cuenta_id', array('tipo_cuenta'), array('stti/tipo_cuenta', 'getListadoTipoCuenta'), array(''=>'Seleccione'), array('class' => 'input-required mask-pint show-error'), $duenio->tipo_cuenta_id, 'Tipo de Cuenta'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::number('duenio.numero_cuenta', array('class' => 'input-required mask-alphanum show-error'), $duenio->numero_cuenta, 'Numero de Cuenta del Banco'); ?>
                        </div>
                    </div>
                </fieldset>
                <div class="row-fluid">
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar Dueño de Puntos'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('stti/duenios/listar/'); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
