<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"stti/duenios/ver/<?php echo $key; ?>/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

        <?php View::process($page_module, $page_title, $set_title); ?>

        <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información del Dueño</a></li>
            <li><a href="#tab2" data-toggle="tab">Puntos asignados</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">
                <?php echo DwForm::open(); ?>
                    <fieldset class="fieldset">
                        <legend><small>Informaci&oacute;n Personal</small></legend>
                        <div class="row-fluid">
                            <div class="span4">
                                <?php echo DwForm::text('duenio.razon_social', array('class' => 'readonly'), $duenio->razon_social, 'Razon Social'); ?>
                            </div>
                            <div class="span4">
                                <?php echo DwForm::text('duenio.identificacion', array('class' => 'readonly'), $duenio->identificacion, 'Identificacion'); ?>
                            </div>
                            <div class="span4">
                                <?php echo DwForm::text('duenio.aprobado', array('class' => 'readonly'), ($duenio->aprobado == Duenio::APROBADO) ? 'APROBADO' : 'RECHAZADO', 'Estado'); ?>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset class="fieldset">
                        <legend><small>Informaci&oacute;n Bancaria</small></legend>
                        <div class='row-fluid'>
                            <div class="span4">
                                <?php echo DwForm::oneSelect('duenio.banco', $duenio->banco, array('class'=>'readonly'), 'Banco'); ?>
                            </div>
                            <div class="span4">
                                <?php echo DwForm::oneSelect('duenio.tipo_cuenta', $duenio->tipo_cuenta, array('class'=>'readonly'), 'Tipo de Cuenta'); ?>
                            </div>
                            <div class="span4">
                                <?php echo DwForm::number('duenio.numero_cuenta', array('class' => 'readonly'), $duenio->numero_cuenta, 'Numero de Cuenta'); ?>
                            </div>
                        </div>
                    </fieldset>
                <?php echo DwForm::close(); ?>
            </div>

            <div class="tab-pane" id="tab2">

                <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th>NUM</th>
                            <th class="col-collapse" data-search="usuario">PUNTO</th>
                            <th class="col-collapse" data-search="nombre">TIPO PUNTO</th>
                            <th class="col-collapse" data-search="apellido">CIUDAD</th>
                            <th class="col-collapse" data-search="apellido">DIRECCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($puntos->items as $punto): ?>
                            <tr>
                                <td><?php echo $puntos->counter; ?></td>
                                <td><?php echo $punto->punto; ?></td>
                                <td><?php echo $punto->tipo_punto; ?></td>
                                <td><?php echo $punto->ciudad; ?></td>
                                <td><?php echo $punto->direccion; ?></td>
                            </tr>
                            <?php $puntos->counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page'=>$puntos, 'url'=>"stti/duenios/ver/$key/$order/")); ?>

            </div>
        </div>

    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::back('stti/duenios/listar/'); ?>
        </div>
    </div>

</div>