<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"stti/puntos/ver/<?php echo $key; ?>/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

        <?php View::process($page_module, $page_title, $set_title); ?>

        <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información del Punto</a></li>
            <li><a href="#tab2" data-toggle="tab">Transacciones asignados</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <?php echo DwForm::open(); ?>
                    <div class="row-fluid">
                        <div class="span4">
                            <?php echo DwForm::oneSelect('punto.duenio', $punto->duenio, array('class'=>'readonly'), 'Dueño del Punto'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('punto.punto', array('class' => 'readonly'), $punto->punto, 'Nombre del Punto'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::oneSelect('punto.tipo_punto', $punto->tipo_punto, array('class'=>'readonly'), 'Tipo de Punto'); ?>
                        </div>
                    </div>
                    <div class='row-fluid'>
                        <div class="span4">
                            <?php echo DwForm::oneSelect('punto.ciudad', $punto->ciudad, array('class'=>'readonly'), 'Ciudad'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('punto.direccion', array('class'=>'readonly'), $punto->direccion, 'Dirección'); ?>
                        </div>
                    </div>
                <?php echo DwForm::close(); ?>
            </div>

            <div class="tab-pane" id="tab2">

                <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th>NUM</th>
                            <th class="col-collapse" data-search="usuario">VALOR</th>
                            <th class="col-collapse" data-search="nombre">ESTADO</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php setlocale(LC_MONETARY, 'es_CO');?>
                        <?php foreach($transacciones->items as $transaccion): ?>
                            <tr>
                                <td><?php echo $transacciones->counter; ?></td>
                                <td>$<?php echo number_format($transaccion->valor, 0, ',', '.'); ?></td>
                                <td><?php echo ($transaccion->estado == Transacciones::PAGADA) ? '<span class="label label-success">Pagada</span>' : '<span class="label label-important">Pendiente</span>'; ; ?></td>
                            </tr>
                            <?php $transacciones->counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page'=>$transacciones, 'url'=>"stti/puntos/ver/$key/$order/")); ?>

            </div>
        </div>

    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::back('stti/puntos/listar/'); ?>
        </div>
    </div>

</div>