<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <?php echo DwForm::hiddenKey('transaccion.id', $transaccion->id)?>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class='row-fluid'>
                    <div class="span4">
                        <?php echo DwForm::dbSelect('transaccion.punto_id', array('punto'), array('stti/punto', 'getListadoPuntos'), array(''=>'Seleccione'), array('class' => 'input-required mask-int show-error'), $transaccion->punto_id, 'Punto'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::text('transaccion.valor', array('class' => 'input-required mask-pint show-error'), $transaccion->valor, 'Valor'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar Transacción'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('stti/transacciones/listar/'); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
