<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"stti/transacciones/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("stti/transacciones/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>
    <div class="dw-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="perfil">PUNTO</th>
                    <th class="col-collapse" data-search="plantilla">VALOR</th>
                    <th class="col-collapse" data-search="usuarios">ESTADO</th>
                    <th class="btn-actions no-responsive">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($transacciones->items as $transaccion): ?>
                    <?php $key_show = DwSecurity::getKey($transaccion->id, 'show_transaccion'); ?>
                    <?php $key_upd = DwSecurity::getKey($transaccion->id, 'upd_transaccion'); ?>
                    <?php $key_pagar = DwSecurity::getKey($transaccion->id, 'pagar_transaccion'); ?>
                    <tr>
                        <td><?php echo $transacciones->counter; ?></td>
                        <td><?php echo $transaccion->punto; ?></td>
                        <td>$<?php echo number_format($transaccion->valor, 0, ',', '.'); ?></td>
                        <td><?php echo ($transaccion->estado == Transacciones::PAGADA) ? '<span class="label label-success">Pagada</span>' : '<span class="label label-important">Pendiente</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Ver Punto', "stti/transacciones/ver/$key_show/", null, 'info', 'search'); ?>
                            <?php if($transaccion->estado == Transacciones::PENDIENTE): ?>
                                <?php echo DwHtml::buttonTable('Modificar Punto', "stti/transacciones/editar/$key_upd/", null, 'info', 'edit'); ?>
                                <?php if(Session::get('perfil_id') == Perfil::SUPER_USUARIO || Session::get('perfil_id') == Perfil::ADMIN):?>
                                    <?php echo DwHtml::buttonTable('Realizar Pago', "stti/transacciones/estado/pagar/$key_pagar/", null, 'success', 'flag'); ?>
                                <?php endif;?>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php $transacciones->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php View::partial('paginators/default', false, array('page'=>$transacciones, 'url'=>"stti/transacciones/listar/$order/")); ?>
</div>