<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"stti/transacciones/ver/<?php echo $key; ?>/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

        <?php View::process($page_module, $page_title, $set_title); ?>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <?php echo DwForm::open(); ?>
                    <div class="row-fluid">
                        <div class="span4">
                            <?php echo DwForm::oneSelect('transaccion.punto', $transaccion->punto, array('class'=>'readonly'), 'Punto'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('transaccion.valor', array('class' => 'readonly'), '$' . number_format($transaccion->valor, 0, ',', '.'), 'Valor de la Transacción'); ?>
                        </div>
                        <div class="span4">
                            <?php echo DwForm::text('transaccion.estado', array('class' => 'readonly'), ($transaccion->estado == Transacciones::PAGADA) ? 'PAGADA' : 'PENDIENTE', 'Estado'); ?>
                        </div>
                    </div>
                <?php echo DwForm::close(); ?>
            </div>
        </div>
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::back('stti/transacciones/listar/'); ?>
        </div>
    </div>
</div>